[Target_Core_Mod/ConfigFS]: Checkpatch fixes
This patch makes target_core_configfs.c return clean for checkpatch.pl, here is the output:

drivers/lio-core/target_core_configfs.c:1: WARNING: patch prefix 'drivers' exists, appears to be a -p0 patch
drivers/lio-core/target_core_configfs.c:476: ERROR: Macros with multiple statements should be enclosed in a do - while loop
drivers/lio-core/target_core_configfs.c:491: ERROR: Macros with multiple statements should be enclosed in a do - while loop
drivers/lio-core/target_core_configfs.c:561: ERROR: Macros with multiple statements should be enclosed in a do - while loop
drivers/lio-core/target_core_configfs.c:819: ERROR: Macros with multiple statements should be enclosed in a do - while loop
total: 4 errors, 1 warnings, 2388 lines checked

I believe the "ERROR: Macros with multiple statements should be enclosed in a do - while loop" on some of
the ConfigFS macros to be a false positive, so it can be safetly ignored for now.

Signed-off-by: Nicholas A. Bellinger <nab@linux-iscsi.org>